<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * AgroecologicalPracticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgroecologicalPracticeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllNewsByPractice($practice)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('n')
            ->from('AppBundle:News', 'n')            
            ->join('AppBundle:AgroecologicalPracticeNews','pn','WITH','n.id = pn.news')
            ->andWhere('pn.agroecological_practice = :practice')
            ->setParameter(':practice', $practice);

        return $qb->getQuery()->getResult();
    }        
}
