<?php

namespace AppBundle\Repository;

/**
 * AgroecologicalPracticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgroecologicalPracticeRepository extends \Doctrine\ORM\EntityRepository
{
}
