<?php

namespace AppBundle\Repository;

/**
 * CaseStudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaseStudyRepository extends \Doctrine\ORM\EntityRepository
{
}
