<?php

namespace AppBundle\Repository;

/**
 * ContactMeanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMeanRepository extends \Doctrine\ORM\EntityRepository
{
}
