<?php

namespace AppBundle\Repository;

/**
 * GoogleMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoogleMapRepository extends \Doctrine\ORM\EntityRepository
{
}
