<?php

namespace AppBundle\Repository;

/**
 * InstitutionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
