<?php

namespace AppBundle\Repository;

/**
 * InstitutionalProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionalProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
