<?php

namespace AppBundle\Repository;

/**
 * KnowledgeAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KnowledgeAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
