<?php

namespace AppBundle\Repository;

/**
 * MarketingSpacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketingSpacesRepository extends \Doctrine\ORM\EntityRepository
{
}
