<?php

namespace AppBundle\Repository;

/**
 * PracticeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PracticeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
