<?php

namespace AppBundle\Repository;

/**
 * ProductiveUndertakingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductiveUndertakingRepository extends \Doctrine\ORM\EntityRepository
{
}
