<?php

namespace AppBundle\Repository;

/**
 * ProductionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
