<?php

namespace AppBundle\Repository;

/**
 * ProductionDestinationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionDestinationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
