<?php

namespace AppBundle\Repository;

/**
 * ProductorProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductorProfileRepository extends \Doctrine\ORM\EntityRepository
{
}
