<?php

namespace AppBundle\Repository;

/**
 * ProductionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
