<?php

namespace AppBundle\Repository;

/**
 * ProfessionalServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
