<?php

namespace AppBundle\Repository;

/**
 * PromotionGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
