<?php

namespace AppBundle\Repository;

/**
 * ReportStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
