<?php

namespace AppBundle\Repository;

/**
 * StudyTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyTopicRepository extends \Doctrine\ORM\EntityRepository
{
}
