<?php

namespace AppBundle\Repository;

/**
 * TopicCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
