app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#Liip imagine routing
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"