# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
        encoders:
            FOS\UserBundle\Model\UserInterface:
                algorithm: bcrypt
                cost: 15

        role_hierarchy:
            ROLE_ADMIN:       [ROLE_INVESTIGATOR, ROLE_PRODUCER]
            ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

        providers:
            in_memory:
                memory:
                    users:
                        admin: { password: adminpass, roles: ['ROLE_SUPER_ADMIN', 'ROLE_ADMIN'] }
            fos_userbundle:
                id: fos_user.user_provider.username

        firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false

            main:
                pattern: ^/
                form_login:
                    provider: fos_userbundle
                    csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                logout:       true
                anonymous:    true

        access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }