<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\AbstractFixture;
use AppBundle\Entity\Institution as InstitutionEntity;

class Institution extends AbstractFixture implements  OrderedFixtureInterface
{
    public function load(ObjectManager $manager)
    {
        $institutions = [
            ['name' => 'Universidad Abierta Interamericana', 'type' => 1],
            ['name' => 'Universidad Adventista del Plata', 'type' => 1],
            ['name' => 'Universidad Argentina de la Empresa', 'type' => 1],
            ['name' => 'Universidad Argentina John F. Kennedy', 'type' => 1],
            ['name' => 'Universidad Atlántida Argentina', 'type' => 1],
            ['name' => 'Universidad Austral', 'type' => 1],
            ['name' => 'Universidad Blás Pascal', 'type' => 1],
            ['name' => 'Universidad CAECE', 'type' => 1],
            ['name' => 'Universidad Católica Argentina', 'type' => 1],
            ['name' => 'Universidad Católica de Córdoba', 'type' => 1],
            ['name' => 'Universidad Católica de Cuyo', 'type' => 1],
            ['name' => 'Universidad Católica de La Plata', 'type' => 1],
            ['name' => 'Universidad Católica de las Misiones', 'type' => 1],
            ['name' => 'Universidad Católica de Salta', 'type' => 1],
            ['name' => 'Universidad Católica de Santa Fe', 'type' => 1],
            ['name' => 'Universidad Católica de Santiago del Estero', 'type' => 1],
            ['name' => 'Universidad Champagnat', 'type' => 1],
            ['name' => 'Universidad de Belgrano', 'type' => 1],
            ['name' => 'Universidad de Ciencias Empresariales y Sociales', 'type' => 1],
            ['name' => 'Universidad de Concepción del Uruguay', 'type' => 1],
            ['name' => 'Universidad de Congreso', 'type' => 1],
            ['name' => 'Universidad de Flores', 'type' => 1],
            ['name' => 'Universidad de la Cuenca del Plata', 'type' => 1],
            ['name' => 'Universidad de la Fraternidad de Agrupaciones Santo Tomás de Aquino', 'type' => 1],
            ['name' => 'Universidad de la Marina Mercante', 'type' => 1],
            ['name' => 'Universidad de Mendoza', 'type' => 1],
            ['name' => 'Universidad de Morón', 'type' => 1],
            ['name' => 'Universidad de Palermo', 'type' => 1],
            ['name' => 'Universidad de San Isidro “Placido Marín”', 'type' => 1],
            ['name' => 'Universidad de San Pablo-Tucumán', 'type' => 1],
            ['name' => 'Universidad de San Andrés', 'type' => 1],
            ['name' => 'Universidad del Aconcagua', 'type' => 1],
            ['name' => 'Universidad del CEMA', 'type' => 1],
            ['name' => 'Universidad del Centro Educativo Latinoamericano', 'type' => 1],
            ['name' => 'Universidad del Cine', 'type' => 1],
            ['name' => 'Universidad del Este', 'type' => 1],
            ['name' => 'Universidad del Museo Social Argentino', 'type' => 1],
            ['name' => 'Universidad del Norte Santo Tomás de Aquino', 'type' => 1],
            ['name' => 'Universidad del Salvador', 'type' => 1],
            ['name' => 'Universidad Empresarial Siglo 21', 'type' => 1],
            ['name' => 'Universidad Favaloro', 'type' => 1],
            ['name' => 'Universidad Gastón Dachary', 'type' => 1],
            ['name' => 'Universidad ISALUD', 'type' => 1],
            ['name' => 'Universidad Juan Agustín Maza ', 'type' => 1],
            ['name' => 'Universidad Notarial Argentina', 'type' => 1],
            ['name' => 'Universidad Maimónides ', 'type' => 1],
            ['name' => 'Universidad Metropolitana para la Educación y el Trabajo', 'type' => 1],
            ['name' => 'Universidad Torcuato Di Tella', 'type' => 1],
            ['name' => 'Universidad Salesiana', 'type' => 1],
            ['name' => 'Universidad de Buenos Aires', 'type' =>2],
            ['name' => 'Universidad de la Defensa Nacional', 'type' =>2],
            ['name' => 'Universidad Nacional Arturo Jauretche', 'type' =>2],
            ['name' => 'Universidad Nacional de Avellaneda', 'type' =>2],
            ['name' => 'Universidad Nacional de Catamarca', 'type' =>2],
            ['name' => 'Universidad Nacional de Chilecito', 'type' =>2],
            ['name' => 'Universidad Nacional de Córdoba', 'type' =>2],
            ['name' => 'Universidad Nacional de Cuyo', 'type' =>2],
            ['name' => 'Universidad Nacional de Entre Ríos', 'type' =>2],
            ['name' => 'Universidad Nacional de Formosa', 'type' =>2],
            ['name' => 'Universidad Nacional de San Martín', 'type' =>2],
            ['name' => 'Universidad Nacional de General Sarmiento', 'type' =>2],
            ['name' => 'Universidad Nacional de Hurlingham', 'type' =>2],
            ['name' => 'Universidad Nacional de José Clemente Paz', 'type' =>2],
            ['name' => 'Universidad Nacional de Jujuy', 'type' =>2],
            ['name' => 'Universidad Nacional de la Matanza', 'type' =>2],
            ['name' => 'Universidad Nacional de la Pampa', 'type' =>2],
            ['name' => 'Universidad Nacional de la Patagonia Austral', 'type' =>2],
            ['name' => 'Universidad Nacional de la Patagonia San Juan Bosco', 'type' =>2],
            ['name' => 'Universidad Nacional de la Plata', 'type' =>2],
            ['name' => 'Universidad Nacional de la Rioja', 'type' =>2],
            ['name' => 'Universidad Nacional de las Artes', 'type' =>2],
            ['name' => 'Universidad Nacional de Lanús', 'type' =>2],
            ['name' => 'Universidad Nacional de Lomas de Zamora', 'type' =>2],
            ['name' => 'Universidad Nacional de los Comechingones', 'type' =>2],
            ['name' => 'Universidad Nacional de Luján', 'type' =>2],
            ['name' => 'Universidad Nacional de Mar del Plata', 'type' =>2],
            ['name' => 'Universidad Nacional de Misiones', 'type' =>2],
            ['name' => 'Universidad Nacional de Moreno', 'type' =>2],
            ['name' => 'Universidad Nacional de Quilmes', 'type' =>2],
            ['name' => 'Universidad Nacional de Rafaela', 'type' =>2],
            ['name' => 'Universidad Nacional de Río Cuarto', 'type' =>2],
            ['name' => 'Universidad Nacional de Río Negro', 'type' =>2],
            ['name' => 'Universidad Nacional de Rosario', 'type' =>2],
            ['name' => 'Universidad Nacional de Salta', 'type' =>2],
            ['name' => 'Universidad Nacional de San Juan', 'type' =>2],
            ['name' => 'Universidad Nacional de San Luis', 'type' =>2],
            ['name' => 'Universidad Nacional de San Antonio de Areco', 'type' =>2],
            ['name' => 'Universidad Nacional de Santiago del Estero', 'type' =>2],
            ['name' => 'Universidad Nacional de Tierra del Fuego, Antartida e Islas del Atlantico Sur', 'type' =>2],
            ['name' => 'Universidad Nacional de Tres de Febrero', 'type' =>2],
            ['name' => 'Universidad Nacional de Tucumán', 'type' =>2],
            ['name' => 'Universidad Nacional de Villa María', 'type' =>2],
            ['name' => 'Universidad Nacional de Villa Mercedes', 'type' =>2],
            ['name' => 'Universidad Nacional Alto Uruguay', 'type' =>2],
            ['name' => 'Universidad Nacional del Centro de la Provincia de Buenos Aires', 'type' =>2],
            ['name' => 'Universidad Nacional del Chaco Austral', 'type' =>2],
            ['name' => 'Universidad Nacional del Comahue', 'type' =>2],
            ['name' => 'Universidad Nacional del Litoral', 'type' =>2],
            ['name' => 'Universidad Nacional del Nordeste', 'type' =>2],
            ['name' => 'Universidad Nacional del Noroeste de la Provincia de Buenos Aires', 'type' =>2],
            ['name' => 'Universidad Nacional del Oeste', 'type' =>2],
            ['name' => 'Universidad Nacional del Sur ', 'type' =>2],
            ['name' => 'Universidad Nacional Raúl Scalabrini Ortiz ', 'type' =>2],
            ['name' => 'Universidad Tecnológica Nacional', 'type' =>2],
            ['name' => 'Administración de Parques Nacionales', 'type' =>3],
            ['name' => 'Administración Nacional de Laboratorios e Institutos de Salud (ANLIS) "Dr. Carlos G. Malbrán"', 'type' =>3],
            ['name' => 'Administración Nacional de Medicamentos, Alimentos y Tecnología Médica (ANMAT)', 'type' =>3],
            ['name' => 'Agencia Nacional de Promoción Científica y Tecnológica', 'type' =>3],
            ['name' => 'Comisión Nacional Asesora de Biotecnología Agropecuaria (CONABIA)', 'type' =>3],
            ['name' => 'Comisión Nacional de Actividades Espaciales (CONAE)', 'type' =>3],
            ['name' => 'Comisión Nacional de Comunicaciones (CNC)', 'type' =>3],
            ['name' => 'Comisión Nacional de Energía Atómica (CNEA)', 'type' =>3],
            ['name' => 'Comisión Nacional de Evaluación y Acreditación Universitaria (CONEAU)', 'type' =>3],
            ['name' => 'Comisión Nacional de Regulación del Transporte (CNRT)', 'type' =>3],
            ['name' => 'Consejo Federal de Ciencia y Tecnología (COFECYT)', 'type' =>3],
            ['name' => 'Consejo Federal de Inversiones (CFI)', 'type' =>3],
            ['name' => 'Consejo Interinstitucional de Ciencia y Tecnología (CICYT)', 'type' =>3],
            ['name' => 'Consejo Interuniversitario Nacional (CIN)', 'type' =>3],
            ['name' => 'Consejo Nacional de Investigaciones Científicas y Técnicas (CONICET)', 'type' =>3],
            ['name' => 'Dirección Nacional de Vialidad (DNV)', 'type' =>3],
            ['name' => 'Empresa Argentina de Soluciones Satelitales (ARSAT)', 'type' =>3],
            ['name' => 'Energía Argentina S. A. (ENARSA)', 'type' =>3],
            ['name' => 'Ente Nacional de Obras Hídricas de Saneamiento (ENOHSA)', 'type' =>3],
            ['name' => 'Ente Nacional Regulador de la Electricidad (ENRE)', 'type' =>3],
            ['name' => 'Ente Nacional Regulador del Gas (ENARGAS)', 'type' =>3],
            ['name' => 'Ente Nacional Regulador Nuclear (ENREN)', 'type' =>3],
            ['name' => 'Fundación Miguel Lillo', 'type' =>3],
            ['name' => 'INNOVA-T', 'type' =>3],
            ['name' => 'Instituto Balseiro', 'type' =>3],
            ['name' => 'Instituto de Geología y Recursos Minerales (IGRM)', 'type' =>3],
            ['name' => 'Instituto de Investigaciones Científicas y Técnicas para la Defensa (CITEFA)', 'type' =>3],
            ['name' => 'Instituto de Tecnología Minera (INTEMIN)', 'type' =>3],
            ['name' => 'Instituto Geográfico Nacional', 'type' =>3],
            ['name' => 'Instituto Nacional de Educación Tecnológica (INET)', 'type' =>3],
            ['name' => 'Instituto Nacional de Estadística y Censos (INDEC)', 'type' =>3],
            ['name' => 'Instituto Nacional de Investigación y Desarrollo Pesquero (INIDEP)', 'type' =>3],
            ['name' => 'Instituto Nacional de la Propiedad Industrial (INPI)', 'type' =>3],
            ['name' => 'Instituto Nacional de Semillas', 'type' =>3],
            ['name' => 'Instituto Nacional de Prevención Sísmica (INPRES)', 'type' =>3],
            ['name' => 'Instituto Nacional de Tecnología Agropecuaria (INTA)', 'type' =>3],
            ['name' => 'Instituto Nacional de Tecnología Industrial (INTI)', 'type' =>3],
            ['name' => 'Instituto Nacional de Vitivinicultura', 'type' =>3],
            ['name' => 'Instituto Nacional del Agua', 'type' =>3],
            ['name' => 'Investigaciones Aplicadas Sociedad del Estado (INVAP)', 'type' =>3],
            ['name' => 'Ministerio de Ciencia, Tecnología e Innovación Productiva', 'type' =>3],
            ['name' => 'Ministerio Industria y Turismo', 'type' =>3],
            ['name' => 'Ministerio de Planificación Federal, Inversión Pública y Servicios', 'type' =>3],
            ['name' => 'Nucleoeléctrica Argentina SA (NA-SA)', 'type' =>3],
            ['name' => 'Organismo Regulador de Seguridad de Presas (ORSEP)', 'type' =>3],
            ['name' => 'Organismo Regulador del Sistema Nacional de Aeropuertos (ORSNA)', 'type' =>3],
            ['name' => 'Órgano de Control de Concesiones Viales (OCCOVI)', 'type' =>3],
            ['name' => 'Servicio Geológico Minero (SEGEMAR)', 'type' =>3],
            ['name' => 'Servicio Nacional de Sanidad y Calidad Agroalimentaria (SENASA)', 'type' =>3]
        ];

        foreach ($institutions as $obj)
        {
            $entity = new InstitutionEntity();
            $type = $manager->getRepository("AppBundle:InstitutionType")->find($obj['type']);
            $entity->setType($type);
            $entity->setName($obj['name']);
            $manager->persist($entity);
        }
        $manager->flush();
    }

    public function getOrder()
    {
        return 8;
    }
}